version: '3'
services:
  postgres_db18:
    image: postgres:14-alpine
    container_name: "postgresdb18"
    environment:
      - "POSTGRES_PASSWORD=123123"
      - "POSTGRES_DB=jehu_terandb"
      - "POSTGRES_USER=jehu_teran"
    ports:
      - "10018:5518"
    volumes:
      - "/home/jehu_teran/postgres:/usr/src/postgres"
    networks:
      - our-library-net
    command: -p 5518

  web18:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && pytest && python manage.py runserver 0.0.0.0:8018"
    container_name: "django18"
    depends_on: 
      - postgres_db18
    environment:
      - "PSQL_DBNAME=jehu_terandb"
      - "PSQL_USERNAME=jehu_teran"
      - "PSQL_PASS=123123"
      - "PSQL_HOST=172.24.0.25"
      - "PSQL_PORT=5518"
    volumes:
    # "RUTA/DEL/SERVIDOR:RUTA/DENTRO/DEL/CONTENEDOR"
      - "/home/jehu_teran/django_test/Django-REST-Exercise:/usr/src/django_test/library"
    ports:
      - "9018:8018"
    networks:
      - our-library-net

networks:
  our-library-net:
    external: true
    driver: bridge